import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Generate a professional PDF report from data
 * @param {Object} options
 * @param {string} options.title - Report title
 * @param {string} options.subtitle - Subtitle
 * @param {Array<{label: string, value: string, color?: string}>} options.kpis - KPI cards
 * @param {Array<{headers: string[], rows: any[][]}>} options.tables - Tables to include
 * @param {string} options.currencySymbol - Currency symbol
 * @param {string} options.filename - Filename (without .pdf)
 */
export async function generatePDFReport(options) {
  const {
    title = 'Report',
    subtitle = '',
    kpis = [],
    tables = [],
    currencySymbol = '$',
    filename = 'report',
  } = options;

  try {
    // Build HTML content
    let tableHTML = '';
    tables.forEach((table, idx) => {
      tableHTML += `
        <h4 style="font-size:14px; font-weight:bold; margin:20px 0 8px 0; color:#1a1a2e;">${table.title || `Table ${idx+1}`}</h4>
        <table style="width:100%; border-collapse:collapse; font-size:11px;">
          <thead>
            <tr>
              ${table.headers.map(h => `<th style="background:#3b82f6; color:#ffffff; padding:6px 10px; text-align:left; font-weight:bold;">${h}</th>`).join('')}
            </tr>
          </thead>
          <tbody>
            ${table.rows.map(row => `
              <tr>
                ${row.map((cell, i) => {
                  const isNumeric = !isNaN(parseFloat(cell)) && i > 0;
                  const align = isNumeric ? 'text-align:right;' : 'text-align:left;';
                  // Color coding if cell starts with + (green) or - (red)
                  let color = '';
                  if (typeof cell === 'string' && cell.startsWith('+')) color = 'color:#10b981;';
                  else if (typeof cell === 'string' && cell.startsWith('-')) color = 'color:#ef4444;';
                  return `<td style="padding:5px 10px; border-bottom:1px solid #e5e7eb; ${align} ${color}">${cell}</td>`;
                }).join('')}
              </tr>
            `).join('')}
          </tbody>
        </table>
      `;
    });

    const kpiHTML = kpis.length > 0 ? `
      <div style="display:grid; grid-template-columns:repeat(${Math.min(kpis.length, 4)}, 1fr); gap:10px; margin:15px 0;">
        ${kpis.map(kpi => `
          <div style="background:#f9fafb; border:1px solid #e5e7eb; border-radius:6px; padding:10px 12px; text-align:center;">
            <div style="font-size:9px; color:#6b7280; text-transform:uppercase;">${kpi.label}</div>
            <div style="font-size:16px; font-weight:bold; color:#1a1a2e; ${kpi.color ? `color:${kpi.color};` : ''}">${kpi.value}</div>
          </div>
        `).join('')}
      </div>
    ` : '';

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            * { margin:0; padding:0; box-sizing:border-box; }
            body { font-family: Arial, Helvetica, sans-serif; background:#ffffff; color:#1a1a2e; padding:30px; width:800px; margin:0 auto; }
            .header { background:#0a0e1a; padding:20px 25px; border-radius:6px 6px 0 0; }
            .header h1 { color:#ffffff; font-size:20px; font-weight:bold; }
            .header .sub { color:#9ca3af; font-size:11px; }
            .header .date { color:#9ca3af; font-size:10px; float:right; margin-top:-22px; }
            .title { font-size:18px; font-weight:bold; margin:20px 0 4px 0; }
            .subtitle { font-size:11px; color:#6b7280; margin-bottom:15px; }
            .footer { margin-top:25px; padding-top:12px; border-top:1px solid #e5e7eb; font-size:9px; color:#6b7280; text-align:center; }
            .footer a { color:#3b82f6; text-decoration:none; font-weight:bold; }
            .footer .brand { color:#3b82f6; font-weight:bold; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>📊 DividendBro</h1>
            <div class="sub">Smart Dividend Investing</div>
            <div class="date">${new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' })}</div>
          </div>

          <div class="title">${title}</div>
          ${subtitle ? `<div class="subtitle">${subtitle}</div>` : ''}

          ${kpiHTML}

          ${tableHTML}

          <div class="footer">
            <span>Generated by <span class="brand">DividendBro</span> — Smart Dividend Investing</span><br>
            <span style="font-size:8px; color:#9ca3af;">Visit us at <a href="https://dividendbro.com">dividendbro.com</a></span>
          </div>
        </body>
      </html>
    `;

    // Create a temporary container
    const container = document.createElement('div');
    container.innerHTML = html;
    container.style.position = 'fixed';
    container.style.top = '-9999px';
    container.style.left = '0';
    container.style.width = '800px';
    container.style.background = '#ffffff';
    container.style.zIndex = '-9999';
    document.body.appendChild(container);

    await new Promise(resolve => setTimeout(resolve, 300));

    const canvas = await html2canvas(container, {
      scale: 2.5,
      backgroundColor: '#ffffff',
      useCORS: true,
      logging: false,
      width: 800,
      height: container.scrollHeight,
    });

    document.body.removeChild(container);

    const imgData = canvas.toDataURL('image/jpeg', 0.95);
    const doc = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = 190;
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

    doc.addImage(imgData, 'JPEG', 10, 10, pdfWidth, pdfHeight);

    // Footer hyperlink
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setDrawColor(209, 213, 219);
    doc.line(15, pageHeight - 12, 195, pageHeight - 12);

    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text('Generated by', 15, pageHeight - 5);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(59, 130, 246);
    doc.text('DividendBro', 40, pageHeight - 5);
    doc.link(40, pageHeight - 10, 35, 8, { url: 'https://dividendbro.com' });

    doc.setTextColor(107, 114, 128);
    doc.text('dividendbro.com', 195, pageHeight - 5, { align: 'right' });
    doc.link(195 - 45, pageHeight - 10, 45, 8, { url: 'https://dividendbro.com' });

    doc.save(`${filename}_${new Date().toISOString().slice(0,10)}.pdf`);
  } catch (error) {
    console.error('PDF generation error:', error);
    throw error;
  }
}